name: jwero_chats
description: A Flutter app for Jwero Chats with local storage and task management.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # State management
  flutter_riverpod: ^2.5.1

  # Faker for mock data
  faker: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
